---
- name: Setup whathappened on a blank server
  hosts: "*"
  gather_facts: yes
  vars_files:
    - vars.yml
  
  vars_prompt:
    - name: db_engine
      prompt: postgresql or mysql?
      private: false

  pre_tasks:
    - name: install packages
      become: yes
      package:
        name:
          - acl
          - git
          - nginx
          - python3-pip
          - supervisor
          - postgresql
          - postgresql-server
        state: latest
        update_cache: yes
    
    - name: check for xterm-kitty file
      stat:
        path: ~/.terminfo/x/xterm-kitty
      register: xterm_kitty

    - name: get kitty term info
      shell: infocmp -x xterm-kitty
      delegate_to: localhost
      register: kitty_term_info
      when: not xterm_kitty.stat.exists

    - name: kitty term info upload
      shell: tic -x -o ~/.terminfo /dev/stdin
      args:
        stdin: "{{ kitty_term_info.stdout }}"
      when: kitty_term_info.stdout is defined

    - name: install mysql
      become: yes
      package:
        name:
        - mysql-server
        state: latest
      when: db_engine == "mysql"
    
    - name: install postgresql
      become: yes
      package:
        name:
          - postgresql
          - postgresql-server
        state: latest
      when: db_engine == "postgresql"

    - name: install venv with pip
      become: yes
      pip:
        name: virtualenv
        executable: pip3
    
    - name: install Psycopg2 with pip globally
      become: yes
      pip:
        name: psycopg2-binary
        executable: pip3

    - name: "Install Psycopg2 with pip"
      pip: "name={{ item }} state=present"
      with_items:
        - psycopg2-binary
      when: db_engine == "postgresql"


    - name: install PyMysql with pip globally
      become: yes
      pip:
        name: PyMySQL
        executable: pip3

    - name: install PyMysql with pip
      pip: "name={{ item }} state=present"
      with_items:
        - PyMySQL
      when: db_engine == "mysql"

  tasks:   
    # PostgreSQL
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data
      become: yes
      when: db_engine == "postgresql"
    
    - name: "Initialize PostgreSQL"
      shell: "postgresql-setup --initdb --unit postgresql"
      when: (db_engine == "postgresql") and (not postgres_data.stat.exists)
      become: yes
    
    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql
      become: yes
      when: db_engine == "postgresql"
      
    - name: Create postgresSQL database
      postgresql_db: 
        state: present
        name: "{{ db_name }}"
      become: yes
      become_user: postgres
      when: db_engine == "postgresql"
    
    - name: User access
      postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
      become: yes
      become_user: postgres
      when: db_engine == "postgresql"

    - name: Grant db access
      postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: no
        privs: all
      become: true
      become_user: postgres
      when: db_engine == "postgresql"
    
    - name: Grant schema public access
      postgresql_privs:
        type: schema
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: no
        privs: all
        objs: public
      become: true
      become_user: postgres
      when: db_engine == "postgresql"



    # Mysql

    - name: Create mysql database
      become: yes
      community.mysql.mysql_db:
        name: whathappened
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      when: db_engine == "mysql"

    # Todo: Set performance_schema = off under [mysqld] in the mysql config

    - name: Create database user for whathappened
      become: yes
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "whathappened.*:ALL"
        host: localhost
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      when: db_engine == "mysql"


    # WhatHappened
    
    - name: copy whathappened
      copy:
        src: ../../dist/whathappened-0.0.2-py3-none-any.whl
        dest: ~/
      register: result

    - name: install whathappened
      pip:
        name: ~/whathappened-0.0.2-py3-none-any.whl
        virtualenv: ~/.venv
        state: forcereinstall
      when: result is changed

    - name: create whathappened config file for postgresql
      copy:
        dest: ~/whathappened_config.env
        content: |
          UPLOAD_FOLDER="uploads"
          SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://{{ db_user }}:{{ db_password }}@localhost:5432/{{ db_name }}"
      when: db_engine == "postgresql"

    - name: create whathappened config file for mysql
      copy:
        dest: ~/whathappened_config.env
        content: |
          UPLOAD_FOLDER="uploads"
          SQLALCHEMY_DATABASE_URI="mysql+pymysql://{{ db_user }}:{{ db_password }}@localhost:3306/{{ db_name }}"
      when: db_engine == "mysql"

    - name: update whathappened database
      shell: WHATHAPPENED_SETTINGS=/home/vagrant/whathappened_config.env FLASK_APP=whathappened ~/.venv/bin/flask db upgrade

    - name: install gunicorn
      pip:
        name: gunicorn
        virtualenv: ~/.venv
        state: latest

    - name: configure supervisor
      become: yes
      copy:
        dest: /etc/supervisor/conf.d/whatappened.conf
        content: |
          [program:whathappened]
          environment=WHATHAPPENED_SETTINGS=/home/vagrant/whathappened_config.env
          command=/home/vagrant/.venv/bin/gunicorn -b localhost:9631 -w 4 "whathappened:create_app()"
          directory=/home/vagrant
          user=vagrant
          autostart=true
          autorestart=true
          stopasgroup=true
          killasgroup=true
      register: result

    - name: reload supervisor
      become: yes
      supervisorctl:
        name: whathappened
        state: restarted
      when: result is changed

    - name: add site settings to nginx
      become: yes
      copy:
        dest: /etc/nginx/sites-available/whathappened
        content: |
          server {
            listen 80;
            server_name _;
            location / {
                    proxy_pass http://localhost:9631;
                    proxy_redirect off;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            location /static {
                    alias /home/vagrant/.venv/lib/python3.10/site-packages/whathappened/static;
                    expires 30d;
            }
          }
      register: result

    - name: disable default nginx site
      become: yes
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: enable whathappened as nginx site
      become: yes
      ansible.builtin.file:
        dest: /etc/nginx/sites-enabled/whathappened
        src: /etc/nginx/sites-available/whathappened
        state: link
      notify: restart nginx

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted
      when: db_engine == "postgresql"

    - name: restart nginx
      become: yes
      ansible.builtin.service:
        name: nginx
        state: restarted
