from setuptools import find_packages, setup

setup(
    name="whathappened",
    version='0.0.2',
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    install_requires=[
        'alembic>=1.8.1',
        'email-validator>=1.3.0',
        'Flask-Login>=0.6.2',
        'Flask-Mail>=0.9.1',
        'Flask-WTF>=1.0.1',
        'flask>=2.2.2',
        'jsonschema>=4.16.0',
        'markdown2>=2.4.6',
        'packaging>=21.3',
        'Pillow>=9.3.0',
        'PyJWT>=2.6.0',
        'pyScss @ git+https://github.com/gregersn/pyScss.git',
        'python-dotenv>=0.21.0',
        'PyMysql>=1.0.2',
        'PyYAML>=6.0.0',
        'SQLAlchemy>=1.4.41',
        'webassets==2.0',
        'jinja2-webpack==0.2.0',
        'pydantic==1.10.2',
        'pywebpack==1.2.0',
    ],
)
