"""add email to users

Revision ID: 243dcd43e639
Revises: d81325dd065a
Create Date: 2020-09-13 08:53:08.538987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243dcd43e639'
down_revision = 'd81325dd065a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
