"""Add invites.

Revision ID: e74859f2a25c
Revises: 6c3ad34a9034
Create Date: 2020-10-03 14:55:25.686154

"""
from alembic import op
import sqlalchemy as sa
from whathappened.database.fields import GUID


# revision identifiers, used by Alembic.
revision = 'e74859f2a25c'
down_revision = '6c3ad34a9034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite',
                    sa.Column('id', GUID(), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=True),
                    sa.Column('table', sa.String(length=128), nullable=True),
                    sa.Column('object_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['owner_id'], ['user_profile.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invite')
    # ### end Alembic commands ###
