"""Add eventlog

Revision ID: c99e163f4457
Revises: 12c624442821
Create Date: 2020-11-08 10:22:50.224838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99e163f4457'
down_revision = '12c624442821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('table', sa.String(length=128), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('entry', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventlog')
    # ### end Alembic commands ###
