"""Add character archive

Revision ID: 02636963a77e
Revises: 879c0232e312
Create Date: 2025-01-03 00:12:47.685702

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "02636963a77e"
down_revision = "879c0232e312"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("charactersheet", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "archived", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("charactersheet", schema=None) as batch_op:
        batch_op.drop_column("archived")

    # ### end Alembic commands ###
