"""Add handout groups

Revision ID: 0373d53a577c
Revises: ac772b7261d0
Create Date: 2020-11-29 18:24:38.363188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0373d53a577c'
down_revision = 'ac772b7261d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_handout_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_campaign_handout_group_campaign_id_campaign')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_handout_group'))
    )
    with op.batch_alter_table('campaign_handout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_campaign_handout_group_id_campaign_handout_group'), 'campaign_handout_group', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_handout', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_campaign_handout_group_id_campaign_handout_group'), type_='foreignkey')
        batch_op.drop_column('group_id')

    op.drop_table('campaign_handout_group')
    # ### end Alembic commands ###
