"""Add user status.

Revision ID: 0e70a6ef92c9
Revises: 02636963a77e
Create Date: 2025-09-13 11:02:44.550028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e70a6ef92c9'
down_revision = '02636963a77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('invited', 'active', 'inactive', 'registered', name='userstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
