"""Add user status.

Revision ID: 0e70a6ef92c9
Revises: 02636963a77e
Create Date: 2025-09-13 11:02:44.550028

"""

from alembic import op
import sqlalchemy as sa

from whathappened.core.auth.models import UserStatusType


# revision identifiers, used by Alembic.
revision = "0e70a6ef92c9"
down_revision = "02636963a77e"
branch_labels = None
depends_on = None


def upgrade():
    UserStatusType.create(op.get_bind(), checkfirst=True)

    ctx = op.get_context()
    dialect = ctx.dialect.name

    new_col = sa.Column("status", UserStatusType, nullable=True)

    # To eliminate 'Skipping unsupported ALTER for creation of implicit
    # constraint' warning we use batch operation to create the new column in
    # case of SQLite.
    if dialect == "sqlite":
        with op.batch_alter_table("user_account") as batch_op:
            batch_op.add_column(new_col)
    else:
        op.add_column("user_account", new_col)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###

    UserStatusType.drop(op.get_bind(), checkfirst=True)
