"""Use JSON for charactersheets.

Revision ID: 155b3a996ca1
Revises: b10c98640b7c
Create Date: 2024-05-10 21:30:46.127617

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "155b3a996ca1"
down_revision = "b10c98640b7c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("charactersheet", schema=None) as batch_op:
        batch_op.alter_column(
            "body",
            existing_type=sa.TEXT(),
            type_=sa.JSON(),
            existing_nullable=True,
            postgresql_using="body::jsonb",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("charactersheet", schema=None) as batch_op:
        batch_op.alter_column(
            "body", existing_type=sa.JSON(), type_=sa.TEXT(), existing_nullable=True
        )

    # ### end Alembic commands ###
