"""Add campaign document option

Revision ID: 4f8f5b9c5e6c
Revises: 02636963a77e
Create Date: 2025-07-06 11:59:35.068150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8f5b9c5e6c'
down_revision = '02636963a77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('document_enabled')

    # ### end Alembic commands ###
