"""Add campaigns

Revision ID: 71a3d1badc2e
Revises: 15525e328d2d
Create Date: 2020-10-04 14:11:35.762861

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "71a3d1badc2e"
down_revision = "15525e328d2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "campaign_characters",
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["charactersheet.id"],
        ),
        sa.PrimaryKeyConstraint("character_id", "campaign_id"),
    )
    op.create_table(
        "campaign_players",
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["user_profile.id"],
        ),
        sa.PrimaryKeyConstraint("player_id", "campaign_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("campaign_players")
    op.drop_table("campaign_characters")
    op.drop_table("campaign")
    # ### end Alembic commands ###
