"""Add display name to user profile

Revision ID: 879c0232e312
Revises: 6f4e81e899a3
Create Date: 2024-12-22 21:47:26.218045

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "879c0232e312"
down_revision = "6f4e81e899a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_profile", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "display_name", sa.String(), nullable=True, server_default=sa.null()
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_profile", schema=None) as batch_op:
        batch_op.drop_column("display_name")

    # ### end Alembic commands ###
