"""Add NPCs to campaign

Revision ID: 8b29c4eb9589
Revises: 0373d53a577c
Create Date: 2020-12-20 02:00:49.815191

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b29c4eb9589"
down_revision = "0373d53a577c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign_npc",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
            name=op.f("fk_campaign_npc_campaign_id_campaign"),
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["charactersheet.id"],
            name=op.f("fk_campaign_npc_character_id_charactersheet"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_npc")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("campaign_npc")
    # ### end Alembic commands ###
