"""Add messages to campaign

Revision ID: a425da83bea3
Revises: 27799ac97853
Create Date: 2021-01-31 16:20:15.256849

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a425da83bea3"
down_revision = "27799ac97853"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("to_id", sa.Integer(), nullable=True),
        sa.Column("from_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
            name=op.f("fk_campaign_message_campaign_id_campaign"),
        ),
        sa.ForeignKeyConstraint(
            ["from_id"],
            ["user_profile.id"],
            name=op.f("fk_campaign_message_from_id_user_profile"),
        ),
        sa.ForeignKeyConstraint(
            ["to_id"],
            ["user_profile.id"],
            name=op.f("fk_campaign_message_to_id_user_profile"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_message")),
    )
    with op.batch_alter_table("campaign_message", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_campaign_message_timestamp"), ["timestamp"], unique=False
        )

    with op.batch_alter_table("campaign", schema=None) as batch_op:
        batch_op.add_column(sa.Column("messages_enabled", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign", schema=None) as batch_op:
        batch_op.drop_column("messages_enabled")

    with op.batch_alter_table("campaign_message", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaign_message_timestamp"))

    op.drop_table("campaign_message")
    # ### end Alembic commands ###
