"""Add handout status

Revision ID: f047bb8f937f
Revises: fae26f355099
Create Date: 2020-10-11 09:18:37.215880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f047bb8f937f"
down_revision = "fae26f355099"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "campaign_handout",
        sa.Column(
            "status",
            sa.Enum("draft", "deleted", "hidden", "visible", name="handoutstatus"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaign_handout", "status")
    # ### end Alembic commands ###
