"""Add handout status

Revision ID: f047bb8f937f
Revises: fae26f355099
Create Date: 2020-10-11 09:18:37.215880

"""

from alembic import op
import sqlalchemy as sa

from whathappened.campaign.models import HandoutStatusType

# revision identifiers, used by Alembic.
revision = "f047bb8f937f"
down_revision = "fae26f355099"
branch_labels = None
depends_on = None


def upgrade():
    HandoutStatusType.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "campaign_handout", sa.Column("status", HandoutStatusType, nullable=True)
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaign_handout", "status")
    # ### end Alembic commands ###

    HandoutStatusType.drop(op.get_bind(), checkfirst=True)
