---
- name: Setup whathappened on a blank server
  hosts: "*"
  tasks:
    - name: install packages
      become: yes
      package:
        name:
          - nginx
          - python3-pip
          - supervisor
        state: latest
        update_cache: yes

    - name: check for xterm-kitty file
      stat:
        path: ~/.terminfo/x/xterm-kitty
      register: xterm_kitty

    - name: get kitty term info
      shell: infocmp -x xterm-kitty
      delegate_to: localhost
      register: kitty_term_info
      when: not xterm_kitty.stat.exists

    - name: kitty term info upload
      shell: tic -x -o ~/.terminfo /dev/stdin
      args:
        stdin: "{{ kitty_term_info.stdout }}"
      when: kitty_term_info.stdout is defined

    - name: install venv with pip
      become: yes
      pip:
        name: virtualenv
        executable: pip3

    - name: copy whathappened
      copy:
        src: ../dist/whathappened-0.0.1-py3-none-any.whl
        dest: ~/
      register: result

    - name: install whathappened
      pip:
        name: ~/whathappened-0.0.1-py3-none-any.whl
        virtualenv: ~/venv
        state: forcereinstall
      when: result is changed

    - name: create whathappened config file
      copy:
        dest: ~/config.py
        content: |
          UPLOAD_FOLDER=uploads

    - name: update whathappened database
      shell: FLASK_APP=whathappened ~/venv/bin/flask db upgrade

    - name: install gunicorn
      pip:
        name: gunicorn
        virtualenv: ~/venv
        state: latest

    - name: configure supervisor
      become: yes
      copy:
        dest: /etc/supervisor/conf.d/whatappened.conf
        content: |
          [program:whathappened]
          command=/home/vagrant/venv/bin/gunicorn -b localhost:9631 -w 4 "whathappened:create_app()"
          directory=/home/vagrant
          user=vagrant
          autostart=true
          autorestart=true
          stopasgroup=true
          killasgroup=true
      register: result

    - name: reload supervisor
      become: yes
      supervisorctl:
        name: whathappened
        state: restarted
      when: result is changed

    - name: add site settings to nginx
      become: yes
      copy:
        dest: /etc/nginx/sites-available/whathappened
        content: |
          server {
            listen 80;
            server_name _;
            location / {
                    proxy_pass http://localhost:9631;
                    proxy_redirect off;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            location /static {
                    alias /home/vagrant/venv/lib/python3.8/site-packages/whathappened/static;
                    expires 30d;
            }
          }
      register: result

    - name: disable default nginx site
      become: yes
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: enable whathappened as nginx site
      become: yes
      ansible.builtin.file:
        dest: /etc/nginx/sites-enabled/whathappened
        src: /etc/nginx/sites-available/whathappened
        state: link
      notify: restart nginx

  handlers:
    - name: restart nginx
      become: yes
      ansible.builtin.service:
        name: nginx
        state: restarted
